name: Get Epic Data

on:
  workflow_dispatch:
  schedule:
    - cron: '5 0 * * *'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout codes
        uses: actions/checkout@v2
        with:
          ref: 'main'
          fetch-depth: 0
          lfs: true
      - name: Set git identity
        run : |
          git config --global user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git config --global user.name "github-actions[bot]"
      - name: Use Node.js
        uses: actions/setup-node@v1
        with:
          node-version: '16.x'
      - name: Cache node modules
        uses: actions/cache@v1
        id: cache
        with:
          path: node_modules
          key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-node-
      - name: Install dependencies
        if: steps.cache.outputs.cache-hit != 'true'
        run: npm install -S
      - name: Run
        run: npm start
      - name: Push Commits
        env:
          TZ: Asia/Shanghai
        run: |
          git add .
          git commit -m 'Daily update'
          git push origin main
