name: Get Epic Data

on:
  schedule:
    - cron: '5 0 * * *'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout codes
        uses: actions/checkout@v2
      with:
        ref: '1.0.0'
        fetch-depth: 0
        lfs: true
      - name: Set git identity
        run : |
          git config --global user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git config --global user.name "github-actions[bot]"
      - name: Use Node.js
        uses: actions/setup-node@v1
        with:
          node-version: '16.x'
      - name: Run
        run: |
          npm install -D
          npm start
      - name: Push Commits
        env:
          TZ: Asia/Shanghai
        run: |
          git add README.md
          git commit -m 'Daily update'
          git push origin 1.0.0
